import type { Project } from '../types'

const gh = 'https://github.com/xenoxf'

export const projects: Project[] = [
  {
    id: 'learnyos',
    name: 'LearnYos',
    description: 'Plataforma de aprendizaje con IA (Next.js)',
    longDescription: 'Frontend de la plataforma educativa LearnYos construido con Next.js 14, React 18 y Tailwind CSS 3. Genera exámenes tipo quiz e ICFES, flashcards y notas con IA, con chat educativo en streaming. Consume la API REST del backend Klerk. Forma parte del sistema Kire junto a Klerk.',
    image: '/images/learnyos.jpg',
    tags: ['frontend', 'Next.js', 'producto', 'IA'],
    tech: ['Next.js 14', 'React 18', 'Tailwind CSS 3', 'TypeScript', 'TanStack Query', 'Zod'],
    githubUrl: `${gh}/learnyos-x2`,
    demoUrl: 'https://learnyos.xenooxf.me',
    backendUrl: `${gh}/klerk`,
    status: 'production',
    maintenance: 'active',
    category: 'frontend',
    isMainTech: true,
    year: 2026,
    purpose: 'Ayudar a estudiantes a preparar exámenes mediante generación con IA de preguntas, flashcards, notas, chat educativo y seguimiento de progreso e intentos.',
    architecture: 'Frontend Next.js 14 (App Router) con React 18 que consume la API REST de Klerk. Estado servidor con TanStack Query, formularios con react-hook-form + Zod, Markdown + KaTeX para contenido educativo, streaming SSE para el chat.',
    role: 'Desarrollador full stack (frontend + integración API)',
    team: 'Individual',
    license: 'AGPL-3.0',
  },
  {
    id: 'klerk',
    name: 'Klerk',
    description: 'API backend con IA para LearnYos (NestJS)',
    longDescription: 'API backend de la plataforma educativa LearnYos. Construida con NestJS 10, TypeORM y PostgreSQL, integra Google Gemini con rotación de keys y fallback de modelos para generar exámenes, flashcards, notas y chat educativo en streaming. Auth con JWT + Google OAuth, créditos diarios, likes y chat global. Licencia AGPL-3.0.',
    image: '/images/klerk.png',
    tags: ['backend', 'API', 'NestJS', 'IA', 'PostgreSQL'],
    tech: ['NestJS 10', 'TypeScript', 'TypeORM', 'PostgreSQL', 'Gemini AI', 'JWT', 'Passport'],
    githubUrl: `${gh}/klerk`,
    status: 'production',
    maintenance: 'active',
    category: 'backend',
    isMainTech: true,
    year: 2026,
    purpose: 'Servir y persistir todo el dominio educativo de LearnYos y orquestar la generación con IA (exámenes, flashcards, notas, chat) con control de costos por créditos.',
    architecture: 'Monolito modular NestJS 10 por features (auth, users, exams, flash-cards, notes, messages, gemini, credits, likes, global-chat, exam-attempts). TypeORM + PostgreSQL, ValidationPipe estricta, Helmet, rate-limit por endpoint, ApiKeyGuard global + JWT.',
    role: 'Desarrollador backend',
    team: 'Individual',
    license: 'AGPL-3.0',
  },
  {
    id: 'sistekpro',
    name: 'Sistek Pro',
    description: 'Sistema full stack corporativo + gestión técnica (Astro + NestJS)',
    longDescription: 'Sistema completo para la empresa Sistek: sitio corporativo en Astro 6 + React 19 con SEO avanzado, páginas por servicio, blog, seguimiento público por QR; más API REST propia en NestJS 11 con TypeORM y PostgreSQL para usuarios, fichas técnicas de equipos, órdenes de servicio, clientes, empleados y leads. Desplegado en Vercel (frontend) y Render (backend).',
    image: '/images/sistek.png',
    tags: ['fullstack', 'corporativo', 'Astro', 'NestJS', 'SEO', 'PostgreSQL'],
    tech: ['Astro 6', 'React 19', 'Tailwind CSS 4', 'NestJS 11', 'TypeORM', 'PostgreSQL', 'JWT'],
    githubUrl: `${gh}/systekpro`,
    demoUrl: 'https://sistekpro.vercel.app',
    backendUrl: `${gh}/sistekpro-backend`,
    backendDemoUrl: 'https://sistekpro-backend.onrender.com',
    status: 'production',
    maintenance: 'active',
    category: 'fullstack',
    isMainTech: true,
    year: 2026,
    purpose: 'Dar presencia web profesional a una empresa de infraestructura y redes, y digitalizar su operación interna: hojas de vida de equipos, órdenes de servicio con timeline y seguimiento público por QR.',
    architecture: 'Frontend: sitio estático/híbrido Astro 6 con islas React 19, Tailwind 4, JSON-LD y sitemap. Backend: API REST modular NestJS 11 (auth, users, ficha_tecnica, ordenes, clientes, empleados, leads, departamentos) con TypeORM + PostgreSQL, auth API Key + JWT por roles (admin/mantenimiento), Helmet + Throttler + class-validator.',
    role: 'Desarrollador full stack',
    team: 'Individual + empresa cliente',
    license: 'Propietario',
  },
  {
    id: 'diamante',
    name: 'Diamante',
    description: 'Sitio institucional + CMS Strapi (Astro + Strapi)',
    longDescription: 'Sistema institucional full stack: frontend en Astro 7 + React 19 con más de 20 páginas (noticias, galería, sedes, especialidades, PQRSF, admisiones) y backend CMS en Strapi 5 con PostgreSQL y Cloudinary para gestionar noticias, galerías, sedes, documentos, slides y solicitudes. Desplegado en diamante-nu.vercel.app.',
    image: '/images/diamante.jpg',
    tags: ['fullstack', 'Astro', 'Strapi', 'CMS', 'PostgreSQL'],
    tech: ['Astro 7', 'React 19', 'Strapi 5', 'PostgreSQL', 'Cloudinary'],
    githubUrl: `${gh}/diamante`,
    demoUrl: 'https://diamante-nu.vercel.app',
    status: 'production',
    maintenance: 'active',
    category: 'fullstack',
    isMainTech: true,
    year: 2026,
    purpose: 'Digitalizar la presencia y gestión de contenido de una institución educativa: noticias, galerías, sedes, especialidades, documentos institucionales y canales de atención ciudadana.',
    architecture: 'Frontend Astro 7 desacoplado que consume la API REST de Strapi 5. Strapi con ~20 content-types (noticia, galeria-item, sede, especialidad, slide-carrusel, solicitud-pqrsf, mensaje-contacto, etc.), PostgreSQL como base y Cloudinary como provider de uploads.',
    role: 'Desarrollador full stack',
    team: 'Individual',
  },
  {
    id: 'killer',
    name: 'Killer',
    description: 'Explorador de archivos desktop (Tauri + Solid + Go + Rust)',
    longDescription: 'Aplicación desktop con Tauri 2 + SolidJS donde el filesystem real vive en Go (sidecar) y Rust actúa como puente IPC por stdio con JSON line-delimited. Incluye ListDir, ReadFile, Tree, Stat, Write y cache reactivo con fallback a mock en modo web. Documentada en README, ARCHITECTURE.md y go/README.md.',
    image: '/images/killer.jpg',
    tags: ['desktop', 'Tauri', 'SolidJS', 'Go', 'Rust'],
    tech: ['Tauri 2', 'SolidJS', 'Go 1.22+', 'Rust', 'TypeScript', 'Vite 6'],
    githubUrl: `${gh}/killer`,
    status: 'development',
    maintenance: 'active',
    category: 'desktop',
    isMainTech: true,
    year: 2026,
    purpose: 'Explorar el filesystem real desde una app desktop ligera, separando responsabilidades: Go para I/O, Rust para IPC seguro y SolidJS para UI reactiva.',
    architecture: 'SolidJS --invoke--> Rust (Tauri go_bridge) --stdio JSON--> Go (internal/fs). Go expone ping/list_dir/read_file/tree/stat/write/delete; Rust lo spawnea como hijo y expone comandos fs_*; frontend usa fsService + fsCache con fallback a mock.',
    role: 'Desarrollador desktop / sistemas',
    team: 'Individual',
    license: 'MIT',
  },
  {
    id: 'xenner',
    name: 'Xenner',
    description: 'Bloc de notas desktop con skins TXT (Tauri + Solid + Rust)',
    longDescription: 'Creador de notas desktop con Tauri 2 + SolidJS + TypeScript + Rust, cuya interfaz es 100% modificable por skins basadas en archivos TXT que el usuario edita. SkinEngine parsea clave="valor" a variables CSS, con skin default glassmorphism embebida y fallback total: una skin rota jamás cuelga la app. Especificación en docs/SKIN_SPEC.md.',
    image: '/images/xenner.png',
    tags: ['desktop', 'Tauri', 'SolidJS', 'Rust', 'UX'],
    tech: ['Tauri 2', 'SolidJS', 'Rust', 'TypeScript', 'Vite 6'],
    githubUrl: `${gh}/xenner`,
    status: 'development',
    maintenance: 'active',
    category: 'desktop',
    isMainTech: true,
    year: 2026,
    purpose: 'Ofrecer un bloc de notas desktop rápido donde el usuario controla toda la apariencia editando TXT simples, sin recompilar ni saber CSS avanzado.',
    architecture: 'Frontend SolidJS con SkinEngine (TXT -> CSS vars --skin-*) + CRUD de notas (fase 1: localStorage). Backend Rust con scan_skins + lectura TXT tolerante a fallos. Ventana transparente Tauri para glassmorphism real.',
    role: 'Desarrollador desktop',
    team: 'Individual',
    license: 'MIT',
  },
  {
    id: 'kluk-dc',
    name: 'KLUK Dashboard',
    description: 'Panel administrativo web (e-commerce)',
    longDescription: 'Panel administrativo web construido con Next.js 16, React 19, Tailwind CSS 4 y TypeScript. Conectado a su propia API (KLUK API). Publicado en kluk-dc.vercel.app.',
    image: '/images/kluk-dc.jpg',
    tags: ['frontend', 'dashboard', 'Next.js', 'e-commerce'],
    tech: ['Next.js 16', 'React 19', 'Tailwind CSS 4', 'TypeScript', 'Axios'],
    githubUrl: `${gh}/kluk-dc`,
    demoUrl: 'https://kluk-dc.vercel.app',
    backendUrl: `${gh}/kluk`,
    status: 'production',
    maintenance: 'stable',
    category: 'frontend',
    isMainTech: true,
    year: 2025,
    purpose: 'Administrar el catálogo y operaciones de un e-commerce desde un panel web.',
    architecture: 'Aplicación Next.js 16 (React 19) con Tailwind CSS 4 que consume la API REST de KLUK con Axios.',
    role: 'Desarrollador frontend',
    team: 'Individual',
  },
  {
    id: 'kluk',
    name: 'KLUK Backend',
    description: 'API backend para un e-commerce',
    longDescription: 'API REST para una plataforma de comercio electrónico, desarrollada con NestJS 10 y TypeScript. Incluye autenticación, usuarios, productos, categorías, carrito, favoritos, reportes y gestión de imágenes con Cloudinary.',
    image: '/images/kluk-dc.jpg',
    tags: ['backend', 'API', 'NestJS', 'e-commerce'],
    tech: ['NestJS 10', 'TypeScript', 'TypeORM', 'PostgreSQL', 'JWT', 'Cloudinary'],
    githubUrl: `${gh}/kluk`,
    status: 'development',
    maintenance: 'active',
    category: 'backend',
    isMainTech: true,
    year: 2026,
    purpose: 'Proveer la API y la persistencia necesarias para gestionar el catálogo, usuarios y operaciones de un e-commerce.',
    architecture: 'API modular construida con NestJS 10 y TypeScript, con TypeORM y PostgreSQL para persistencia, JWT y guards para autorización, Swagger para documentación y Cloudinary para imágenes.',
    role: 'Desarrollador backend',
    team: 'Individual',
  },
  {
    id: 'back-os',
    name: 'Back-OS',
    description: 'API backend con Express y Prisma',
    longDescription: 'API backend desarrollada con Express 5, Prisma y TypeScript, con autenticación JWT + Google OAuth, rate-limit, Helmet, validación Zod y envío de correos con Nodemailer.',
    image: '/images/back-os.jpg',
    tags: ['backend', 'API', 'TypeScript', 'Express', 'Prisma'],
    tech: ['Express 5', 'Prisma', 'TypeScript', 'PostgreSQL', 'JWT', 'Zod'],
    githubUrl: `${gh}/back-OS`,
    status: 'production',
    maintenance: 'stable',
    category: 'backend',
    isMainTech: true,
    year: 2025,
    purpose: 'Proveer una API REST con autenticación y persistencia para aplicaciones web.',
    architecture: 'API REST con Express 5 y capa de datos con Prisma en TypeScript. Middlewares propios requireAuth/requireKey, Helmet, express-rate-limit y validación con Zod.',
    role: 'Desarrollador backend',
    team: 'Individual',
    license: 'ISC',
  },
  {
    id: 'pomodoro-react',
    name: 'Pomodoro React',
    description: 'Temporizador Pomodoro',
    longDescription: 'Aplicación de temporizador Pomodoro construida con Vite 6 y React 19. Publicada en pomodoro-react-black.vercel.app.',
    image: '/images/pomodoro.png',
    tags: ['frontend', 'React', 'aprendizaje'],
    tech: ['Vite 6', 'React 19'],
    githubUrl: `${gh}/PomodoroReact`,
    demoUrl: 'https://pomodoro.xenooxf.me',
    status: 'production',
    maintenance: 'stable',
    category: 'frontend',
    isMainTech: false,
    year: 2025,
    purpose: 'Aplicación de productividad para gestionar sesiones de trabajo con la técnica Pomodoro.',
    architecture: 'Single Page Application con Vite 6 y React 19, sin backend. Estado local con hooks.',
    role: 'Desarrollador frontend',
    team: 'Individual',
  },
  {
    id: 'juntxo-player',
    name: 'Juntxo Player',
    description: 'Reproductor de música en Java (CLI)',
    longDescription: 'Reproductor de música desde la terminal desarrollado en Java. Proyecto de aprendizaje del lenguaje.',
    image: '/images/juntxo-player.png',
    tags: ['cli', 'Java', 'audio'],
    tech: ['Java'],
    githubUrl: `${gh}/juntxo-player`,
    status: 'development',
    maintenance: 'stable',
    category: 'cli',
    isMainTech: false,
    year: 2026,
    purpose: 'Reproducir música desde la consola como ejercicio de aprendizaje de Java.',
    architecture: 'Aplicación de consola en Java (CLI).',
    role: 'Desarrollador',
    team: 'Individual',
  },
]

export function getProject(id: string): Project | undefined {
  return projects.find((p) => p.id === id)
}

export function getRelatedProjects(id: string, limit = 3): Project[] {
  const current = getProject(id)
  if (!current) return []
  return projects
    .filter((p) => p.id !== id)
    .sort((a, b) => {
      const aScore = (a.category === current.category ? 2 : 0) + a.tech.filter((t) => current.tech.some((ct) => ct.split(' ')[0] === t.split(' ')[0])).length
      const bScore = (b.category === current.category ? 2 : 0) + b.tech.filter((t) => current.tech.some((ct) => ct.split(' ')[0] === t.split(' ')[0])).length
      return bScore - aScore
    })
    .slice(0, limit)
}
