import type { Project } from '../types'

const gh = 'https://github.com/xenoxf'

export const projects: Project[] = [
  {
    id: 'kire',
    name: 'Klerk / LearnYos',
    description: 'Plataforma de aprendizaje activo con IA',
    longDescription: 'Plataforma educativa estilo Quizlet/Duolingo para estudiantes que preparan ICFES/Saber 11. Genera exámenes tipo ICFES, flashcards y notas con Gemini AI. Incluye chat con tutor IA (Junior), sistema de créditos diarios (freemium), likes comunitarios, chat global, y seguimiento de intentos de exámenes. Backend NestJS 10 con TypeORM + PostgreSQL en Aiven Cloud. Frontend Next.js 14 con React Query, Radix UI, Tailwind CSS, i18n, y PWA. 3 niveles de autenticación (API Key + JWT + Google OAuth).',
    image: '/images/learnyos.jpg',
    tags: ['Fullstack', 'IA', 'educación'],
    tech: ['NestJS', 'Next.js 14', 'TypeORM', 'PostgreSQL', 'Gemini AI', 'Render', 'Vercel'],
    githubUrl: `${gh}/kire`,
    demoUrl: 'https://learnyos.vercel.app',
    backendUrl: 'https://klerk.onrender.com',
    status: 'production',
    maintenance: 'active',
    category: 'fullstack',
    isMainTech: true,
    year: 2025,
    subProjects: [
      { name: 'Klerk (Backend)', tech: 'NestJS 10 · TypeORM · PostgreSQL · Gemini AI · JWT · OAuth · Render', url: 'https://klerk.onrender.com' },
      { name: 'LearnYos (Frontend)', tech: 'Next.js 14 · React 18 · Radix UI · Tailwind · React Query · i18n · PWA · Vercel', url: 'https://learnyos.vercel.app' },
    ],
  },
  {
    id: 'sistek',
    name: 'Sistek Pro',
    description: 'Sitio web corporativo para empresa de TI',
    longDescription: 'Sitio web profesional para Sistek, empresa de infraestructura tecnológica y redes en Cali, Colombia, con 6 páginas de servicio (mantenimiento, redes empresariales, cableado estructurado, configuración de routers/switches, WiFi empresarial, soporte técnico), blog, FAQ con schema JSON-LD, formulario de contacto con Formspree, y botón flotante de WhatsApp. SEO completo con datos estructurados (LocalBusiness, Organization, Service, FAQPage, BlogPosting, BreadcrumbList), sitemap dinámico, hreflang, Open Graph, Twitter Cards. Tema oscuro/claro con persistencia en localStorage. Construido con Astro 6 y Tailwind CSS 4.',
    image: '/images/sistek.jpg',
    tags: ['frontend', 'SEO', 'corporativo'],
    tech: ['Astro 6', 'React 19', 'Tailwind CSS 4', 'Radix UI', 'Formspree'],
    githubUrl: `${gh}/sistek`,
    demoUrl: 'https://sistekpro.vercel.app',
    status: 'production',
    maintenance: 'active',
    category: 'frontend',
    isMainTech: true,
    year: 2026,
  },
  {
    id: 'kluk-api',
    name: 'KLUK API',
    description: 'API REST para e-commerce',
    longDescription: 'Backend de e-commerce con NestJS 10 y TypeORM sobre PostgreSQL en Aiven Cloud. Gestión de productos con categorías, carrito de compras, favoritos, subida de imágenes a Cloudinary, panel de reportes y documentación Swagger completa.',
    tags: ['backend', 'e-commerce', 'API'],
    tech: ['NestJS 10', 'TypeORM', 'PostgreSQL', 'Cloudinary', 'Swagger'],
    githubUrl: `${gh}/kluk`,
    backendUrl: 'https://kluk.onrender.com',
    status: 'production',
    maintenance: 'archived',
    category: 'backend',
    isMainTech: true,
    year: 2025,
  },
  {
    id: 'kluk-dc',
    name: 'KLUK Dashboard',
    description: 'Dashboard administrativo web + desktop',
    longDescription: 'Panel de administración para KLUK con versión web (Next.js 16) y aplicación de escritorio (Tauri 2 con Rust). Incluye autenticación, gestión de productos/categorías, reportes con gráficos Recharts y modo demo.',
    tags: ['frontend', 'desktop', 'dashboard'],
    tech: ['Next.js 16', 'React 19', 'Tauri 2', 'Rust', 'Tailwind CSS 4', 'Recharts', 'shadcn/ui'],
    githubUrl: `${gh}/kluk-dc`,
    status: 'production',
    maintenance: 'archived',
    category: 'desktop',
    isMainTech: true,
    year: 2025,
  },
  {
    id: 'back-os',
    name: 'Back-OS',
    description: 'API backend con Express y Prisma',
    longDescription: 'API monolítica con Express 5 y Prisma ORM sobre PostgreSQL. Sistema completo de autenticación (JWT + Google OAuth), flashcards organizadas por mazos, notas, chat con respuestas automáticas, perfiles de usuario y eliminación de cuenta con ventana de 48h.',
    tags: ['backend', 'API', 'autenticación'],
    tech: ['Express 5', 'Prisma', 'PostgreSQL', 'JWT', 'Zod', 'Google OAuth'],
    githubUrl: `${gh}/back-os`,
    status: 'production',
    maintenance: 'archived',
    category: 'backend',
    isMainTech: true,
    year: 2025,
  },
  {
    id: 'aximu',
    name: 'Aximu v2',
    description: 'E-commerce API con Spring Boot y Java',
    longDescription: 'API REST de e-commerce construida con Java 21 y Spring Boot 3.5. Catálogo con filtros dinámicos por género, categoría, color y marca. Carrito de compras, favoritos, autenticación JWT + API Key con rate limiting. Documentado con Swagger.',
    tags: ['backend', 'e-commerce', 'Java'],
    tech: ['Spring Boot 3.5', 'Java 21', 'PostgreSQL', 'JWT', 'Swagger', 'Maven'],
    githubUrl: `${gh}/aximu_v2`,
    status: 'production',
    maintenance: 'archived',
    category: 'backend',
    isMainTech: false,
    year: 2025,
  },
  {
    id: 'juntxo-player',
    name: 'Juntxo Player',
    description: 'Reproductor de música CLI en Java',
    longDescription: 'Reproductor MP3 desde terminal con Java 21 y Maven. Escanea directorios de música, lee metadatos ID3 (título, artista, álbum, género), y permite reproducir, pausar, listar y aleatorizar canciones. Proyecto personal para aprender Java.',
    tags: ['cli', 'Java', 'audio'],
    tech: ['Java 21', 'Maven', 'JLayer', 'mp3agic', 'Gson'],
    githubUrl: `${gh}/juntxo-player`,
    status: 'production',
    maintenance: 'archived',
    category: 'cli',
    isMainTech: false,
    year: 2025,
  },
]
